spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
  application:
    name: ORDER-SERVICE


logging:
  file: C:\microservice\Spring-Boot-Spring-Cloud\logs\microservice.log

server:
  port: 9191