server:
  port: 9091
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
  application:
    name: PAYMENT-SERVICE


logging:
  file: C:\microservice\Spring-Boot-Spring-Cloud\logs\microservice.log





